import '../globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* 👇 suppress hydration mismatch warnings */}
      <body suppressHydrationWarning={true}>{children}</body>
    </html>
  )
}
